### ISSUE TITLE
Core file missing the other thread stack frame 

### ISSUE THREAD

**Issue by Haoqian-He** [diamon/minicoredumper#13]
Hi minicoredumper experts
I run the minicoredumer to generate the core file, but i found the output core missing the important info of the other thread stack(Not the crashed thread),  like this :
```
(gdb) bt
#0  0x00007f1d597c73fa in poll() from /lib64/libc.so
#1  0x0000000000000000 in ?? ()
```
Only the stack of the crashing thread is complete and I don't know if it meets expectations.
My generic.recept.json is: 
```
{
    "stacks": {
        "dump_stacks": true,
        "first_thread_only": false,
        "max_stack_size": 0
    },
    "maps": {
        "dump_by_name": [
            "[vdso]"
        ]
    },
    "compression": {
        "compressor": "zstd",
        "extension": "zst",
        "in_tar": false
    },
    "dump_auxv_so_list": true,
    "dump_pthread_list": true,
    "dump_robust_mutex_list": true,
    "dump_scope": 1024,
    "live_dumper": false,
    "write_proc_info": false,
    "write_debug_log": false,
    "dump_fat_core": false
}
```

Thanks.

**Comment by jogness** [comment]
This is a known problem due to a bug in the kernel. Please see [this post](https://lists.linutronix.de/pipermail/minicoredumper/2023-September/000146.html) for a brief explanation and workaround/hack kernel patch.

**Comment by Haoqian-He** [comment]
> This is a known problem due to a bug in the kernel. Please see [this post](https://lists.linutronix.de/pipermail/minicoredumper/2023-September/000146.html) for a brief explanation and workaround/hack kernel patch.

Thanks for u'r reply, i saw your patch in [lkml](https://lore.kernel.org/lkml/87pno0u59o.fsf_-_@linutronix.de/)

**Comment by jogness** [comment]
> i saw your patch in [lkml](https://lore.kernel.org/lkml/87pno0u59o.fsf_-_@linutronix.de/)

Note that the patch you cited is a _different_ patch. That was a previous time that /proc/PID/stat was broken.

I have not yet submitted a patch for the current problem because I also want to submit a kselftest with it and I have not had time for this yet.

I am reopening this issue because it is a valid issue since kernel 5.18.

**Comment by jogness** [comment]
The problem with capturing stacks of non-crashing threads will finally be fixed for Linux 6.14, broken since 5.18.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/proc/array.c?id=ab251dacfbae28772c897f068a4184f478189ff2
